### ISSUE TITLE
Able to pass the test with a function that does nothing

### ISSUE THREAD

**Issue by sparklie3** [learn-co-curriculum/introduction-to-array-for-each#3]
I was able to pass the test with the following code with the function doing nothing: 

```
function changeCompletely(element, index, array){}

function doToElementsInArray(array, callback) {}

```

https://github.com/sparklie3/introduction-to-array-for-each-js-intro-000/blob/master/index.js

This seems like a cheat that shouldn't be allowed. 

I think this is because the test is passing because undefined != array with what I see in the index-test.js

```
it('completely alters an array in place when used with Array.prototype.forEach', () => {
      const array = [1, 2, 3]
      expect(array.forEach(changeCompletely)).not.to.eql([1, 2, 3])
    })

```

I'm not sure why the second test passes since I'm still play around to better understand callback

**Comment by AnnJohn** [comment]
hi @sparklie3 sorry for the delay. since this looks like a conceptual question that you have, could you use Ask a Question and someone from our team will help you out right away. Thanks!
