### ISSUE TITLE
Passing Test

### ISSUE THREAD

**Issue by redjake** [learn-co-curriculum/introduction-to-array-for-each#6]
The Function changeCompletely passes in the console without having to put code in the function.

**Comment by gj** [comment]
cc: @aturkewi @cernanb

ETA: To clarify, this + https://github.com/learn-co-curriculum/introduction-to-array-for-each/issues/4 go hand-in-hand. The following code passes all tests in the code-along:
```js
function changeCompletely () { }

function doToElementsInArray () { }
```
